# Generated by Django 2.0.7 on 2019-07-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Date',
        ),
    ]
