# Generated by Django 2.0.7 on 2019-07-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_customer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=30)),
                ('Amount', models.IntegerField()),
                ('Investment_Type', models.CharField(max_length=30)),
            ],
        ),
    ]
